// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Url.Infrastructure;

#nullable disable

namespace Url.Infrastructure.Migrations
{
    [DbContext(typeof(LinkPulseDbContext))]
    [Migration("20251210132635_InitialCreate_Url")]
    partial class InitialCreate_Url
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Url.Domain.ShortUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ShortUrls");
                });

            modelBuilder.Entity("Url.Domain.ShortUrl", b =>
                {
                    b.OwnsOne("Url.Domain.Url", "OriginalUrl", b1 =>
                        {
                            b1.Property<Guid>("ShortUrlId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("OriginalUrl");

                            b1.HasKey("ShortUrlId");

                            b1.ToTable("ShortUrls");

                            b1.WithOwner()
                                .HasForeignKey("ShortUrlId");
                        });

                    b.Navigation("OriginalUrl")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
